services:
  reports_service:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-django
    container_name: reports_service
    restart: always
    ports:  
      - "8002:8000"
    environment:
      DJANGO_ENV: development
      DB_HOST: mysql_reports
      DB_NAME: reports_db
      DB_USER: reports_user        
      DB_PASSWORD: reportspassword
    depends_on:
      - mysql_reports

  mysql_reports:
    image: mysql:8.0
    container_name: mysql_reports
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reports_db
      MYSQL_USER: reports_user
      MYSQL_PASSWORD: reportspassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_reports_data:/var/lib/mysql
    networks:
      - reports_network

volumes:
  mysql_reports_data: