services:
  mysql_auth:
    image: mysql:8.0
    container_name: mysql_auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    ports:
      - "3306:3306"
    volumes:
      - auth_data:/var/lib/mysql
      
volumes:
  auth_data: